# Generated by Django 2.2.1 on 2020-01-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name="Site's url")),
                ('news_css', models.CharField(max_length=255, verbose_name='CSS path to piece of news tag')),
                ('title_css', models.CharField(max_length=255, verbose_name='CSS path (inside news tag) to title')),
                ('sub_title_css', models.CharField(max_length=255, verbose_name='CSS path (inside news tag) to subtitle')),
                ('description_css', models.CharField(max_length=255, verbose_name='CSS path (inside news tag) to description')),
                ('link_css', models.CharField(max_length=255, verbose_name='CSS path (inside news tag) to link')),
                ('time_css', models.CharField(max_length=255, verbose_name='CSS path (inside news tag) to publication date')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, unique=True, verbose_name='Title')),
                ('sub_title', models.TextField(null=True, verbose_name='Subtitle')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('time', models.CharField(max_length=255, null=True, verbose_name='Publication date')),
                ('link', models.CharField(max_length=255, null=True, verbose_name='Link')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Parsed at')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.Site', verbose_name='Site')),
            ],
        ),
    ]
