# Generated by Django 2.2.1 on 2020-01-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='sub_title',
            field=models.TextField(null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(null=True, unique=True, verbose_name='Title'),
        ),
    ]
