version: '3.4'
services:
    server:
      build:
        context: ./
        dockerfile: ./server/Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./server:/server
      ports:
        - "8000:8000"
      depends_on:
        - db
        - celery
      environment:
          DEBUG: 'True'
          DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
          BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'


    rabbitmq:
        image: rabbitmq:3.7.5
        environment:
            RABBITMQ_DEFAULT_USER: 'user'
            RABBITMQ_DEFAULT_PASS: 'password'
            RABBITMQ_DEFAULT_VHOST: 'my_vhost'

    celery:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        command: celery -A parsing worker -B -l info -Q default,celery -s /var/run/celerybeat-schedule
        volumes:
            - ./server:/server
        depends_on:
            - db
            - rabbitmq
        environment:
            DEBUG: 'True'
            DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
            BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'

    db:
      image: postgres:11.2
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres

    vue:
      build:
        context: ./
        dockerfile: ./vue-spa/Dockerfile
        command: http-server
      depends_on:
        - server
      expose:
        - 8080
      ports:
        - 8080:8080

